import { StyleSheet } from 'react-native';

import { colors, radii, spacing } from '@/theme';
import { tabletColors, tabletLayout } from '@/theme/tabletColors';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background },
  searchWrap: { flexDirection: 'row', paddingHorizontal: spacing.base, marginBottom: spacing.md, gap: spacing.sm },
  searchWrapTablet: { paddingHorizontal: 20, marginBottom: spacing.base, gap: 10 },
  searchInput: { flex: 1 },
  scanIconButton: {
    width: 50,
    height: 50,
    borderRadius: radii.md,
    borderWidth: 1.5,
    borderColor: colors.borderStrong,
    backgroundColor: colors.background,
    alignItems: 'center',
    justifyContent: 'center',
  },
  scanIconButtonTablet: {
    width: 46,
    height: 46,
    borderWidth: 1,
    borderColor: tabletColors.gray200,
    backgroundColor: tabletColors.white,
  },
  sessionBanner: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.sm,
    marginHorizontal: spacing.base,
    marginBottom: spacing.sm,
    padding: spacing.base,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.warning[200],
    backgroundColor: colors.warning[50],
  },
  sessionBannerGlyph: {
    width: 34,
    height: 34,
    borderRadius: radii.md,
    backgroundColor: colors.warning[100],
    alignItems: 'center',
    justifyContent: 'center',
  },
  sessionBannerInfo: { flex: 1 },
  sessionBannerTitle: { color: colors.warning[700], marginBottom: 2 },
  sessionBannerText: { color: colors.warning[700] },
  sessionBannerButton: { alignSelf: 'flex-start', marginTop: spacing.sm },
  categoryRow: { paddingHorizontal: spacing.base, paddingBottom: 10, gap: spacing.sm, alignItems: 'center' },
  categoryRowTablet: { paddingHorizontal: 20, paddingBottom: 0 },
  chip: {
    paddingHorizontal: spacing.base,
    paddingVertical: spacing.sm,
    borderRadius: 9999,
    backgroundColor: colors.background,
    borderWidth: 1,
    borderColor: colors.border,
    marginRight: spacing.sm,
  },
  chipActive: { backgroundColor: colors.primary[600], borderColor: colors.primary[600] },
  chipTablet: {
    paddingHorizontal: 18,
    paddingVertical: 8,
    borderColor: tabletColors.gray200,
    backgroundColor: tabletColors.white,
  },
  chipActiveTablet: { backgroundColor: tabletColors.navy900, borderColor: tabletColors.navy900 },
  chipLabelTablet: { color: tabletColors.gray600 },
  body: { flex: 1, flexDirection: 'row' },
  leftColumn: { flex: 1 },
  gridList: { flex: 1 },
  grid: { paddingHorizontal: spacing.base, paddingBottom: 96 },
  gridTabletPadding: { paddingHorizontal: 20, paddingBottom: spacing.md },
  gridRow: { gap: spacing.md },
  gridRowTablet: { gap: 14 },
  sidePanel: {
    width: 360,
    borderLeftWidth: 1,
    borderLeftColor: tabletColors.gray150,
    backgroundColor: tabletColors.white,
  },
  sidePanelInner: { flex: 1, padding: spacing.base },
  sidePanelHeader: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between' },
  sidePanelHeaderText: { flex: 1 },
  sidePanelTitleTablet: { fontSize: 15, fontWeight: '700', color: tabletColors.gray900 },
  sidePanelMetaTablet: { fontSize: 11.5, color: tabletColors.gray500, marginTop: 4 },
  clearIconButton: {
    width: 32,
    height: 32,
    borderRadius: radii.md,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.background,
  },
  sidePanelList: { flex: 1, marginTop: spacing.sm },
  sidePanelEmpty: { alignItems: 'center', justifyContent: 'center', paddingVertical: spacing.xl },
  sidePanelEmptyGlyph: {
    width: 56,
    height: 56,
    borderRadius: radii.xl,
    backgroundColor: colors.primary[50],
    alignItems: 'center',
    justifyContent: 'center',
  },
  sidePanelEmptyText: { marginTop: spacing.xs, textAlign: 'center' },
  summaryDivider: { height: StyleSheet.hairlineWidth, backgroundColor: colors.border, marginVertical: spacing.sm },
  summaryDividerTablet: { height: 1, backgroundColor: tabletColors.gray150, marginTop: spacing.sm, marginBottom: 2 },
  summaryRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: spacing.xs },
  summaryRowTablet: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 6 },
  summaryLabelTablet: { fontSize: 13, color: tabletColors.gray600 },
  summaryValueTablet: { fontSize: 13, color: tabletColors.gray600 },
  discountLabel: { marginTop: spacing.sm, marginBottom: spacing.xs },
  discountRow: { flexDirection: 'row', gap: spacing.sm, alignItems: 'stretch' },
  discountTypeToggle: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
    paddingHorizontal: spacing.md,
    borderRadius: radii.md,
    borderWidth: 1.5,
    borderColor: colors.borderStrong,
    backgroundColor: colors.background,
  },
  discountInput: { flex: 1 },
  ppnRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: spacing.md,
    marginBottom: spacing.lg,
  },
  totalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: spacing.sm,
    paddingTop: spacing.sm,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: colors.border,
  },
  totalRowTablet: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 6,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: tabletColors.gray150,
  },
  totalLabelTablet: { fontSize: 15, fontWeight: '700', color: tabletColors.gray900 },
  totalValueTablet: { fontSize: 22, fontWeight: '800', color: tabletColors.navy900 },
  actionRow: { flexDirection: 'row', gap: spacing.sm, marginTop: spacing.base },
  actionButton: {
    flex: 1,
    alignItems: 'center',
    gap: 2,
    paddingVertical: spacing.sm,
    borderRadius: radii.md,
    borderWidth: 1.5,
    borderColor: colors.border,
    backgroundColor: colors.background,
  },
  actionButtonTablet: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    minHeight: tabletLayout.touchTargetMinHeight,
    paddingVertical: 6,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: tabletColors.gray300,
    backgroundColor: tabletColors.white,
  },
  actionButtonLabelTablet: { fontSize: 12.5, fontWeight: '600', color: tabletColors.gray700 },
  payButton: { marginTop: spacing.base },
  payButtonTablet: { backgroundColor: tabletColors.blue600, minHeight: tabletLayout.touchTargetMinHeight },
  card: { flex: 1, marginBottom: spacing.md, borderRadius: radii.lg, overflow: 'hidden' },
  cardImageWrap: {
    width: '100%',
    aspectRatio: 1 / 0.8,
    alignItems: 'center',
    justifyContent: 'center',
    borderTopLeftRadius: radii.lg,
    borderTopRightRadius: radii.lg,
  },
  cardImageWrapTablet: { aspectRatio: 1 / 0.85 },
  cardImage: { width: '100%', height: '100%', borderTopLeftRadius: radii.lg, borderTopRightRadius: radii.lg },
  cardBody: { padding: spacing.sm, flex: 1, justifyContent: 'space-between' },
  cardBodyTablet: { padding: 14 },
  cardName: { minHeight: 34 },
  cardFooter: { marginTop: spacing.xs, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  empty: { marginTop: spacing['3xl'] },
  cartBar: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: colors.gray[900],
    padding: spacing.base,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  cartLabelRow: { flexDirection: 'row', alignItems: 'center', gap: 4, marginBottom: 2 },
  cartLabel: { color: colors.gray[300] },
  cartText: { color: colors.white },
  cartRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    paddingVertical: spacing.sm,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
  },
  cartRowTablet: { paddingVertical: 12, borderBottomColor: tabletColors.gray100 },
  cartRowThumbnail: {
    width: 40,
    height: 40,
    borderRadius: radii.md,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cartRowThumbnailTablet: { width: 44, height: 44, borderRadius: 9 },
  cartRowInfo: { flex: 1 },
  cartRowNameTablet: { fontSize: 13, color: tabletColors.gray900 },
  cartRowPriceTablet: { fontSize: 11.5, color: tabletColors.gray500, marginTop: 2 },
  stepper: { flexDirection: 'row', alignItems: 'center', gap: spacing.xs },
  stepperTablet: { gap: 8 },
  stepperButton: {
    width: 26,
    height: 26,
    borderRadius: radii.sm,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepperButtonTablet: { width: 30, height: 30, borderRadius: 6, borderColor: tabletColors.gray300, backgroundColor: tabletColors.white },
  stepperGlyphTablet: { fontSize: 12.5, color: tabletColors.gray600 },
  stepperQtyBox: {
    minWidth: 26,
    height: 26,
    borderRadius: radii.sm,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.xs,
  },
  stepperQtyBoxTablet: {
    minWidth: 14,
    height: 18,
    borderRadius: 0,
    borderWidth: 0,
    backgroundColor: 'transparent',
    paddingHorizontal: 0,
  },
  modalTitle: { marginBottom: spacing.base },
  modalTitleRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.xs, marginBottom: spacing.base },
  unitPickerHint: { marginBottom: spacing.base },
  openSessionHint: { marginBottom: spacing.base },
  unitChoice: { marginBottom: spacing.sm },
  modalActions: { flexDirection: 'row', justifyContent: 'flex-end', gap: spacing.sm, marginTop: spacing.sm },
  modalAction: { minWidth: 90 },
  checkoutTotalBox: {
    backgroundColor: colors.surface,
    borderRadius: radii.md,
    padding: spacing.base,
    marginBottom: spacing.base,
    gap: spacing.xs,
  },
  checkoutTotalRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  paymentMethodRow: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm },
  paymentChip: {
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderRadius: 9999,
    borderWidth: 1.5,
    borderColor: colors.borderStrong,
    backgroundColor: colors.background,
  },
  paymentChipActive: { backgroundColor: colors.primary[600], borderColor: colors.primary[600] },
  presetRow: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm, marginBottom: spacing.base },
  presetChip: {
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  itemsSection: { marginTop: spacing.sm },
  itemsSectionTitle: { marginBottom: spacing.xs },
  changeBox: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginVertical: spacing.sm,
  },
  debtBox: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginVertical: spacing.sm,
    padding: spacing.sm,
    borderRadius: radii.md,
    backgroundColor: colors.error[50],
  },
});
